article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"
# article icerisindeki url yonlendirmelerini buradan yapacagız
# daha moduler hale getirmek icin buna basvurduk

urlpatterns = [
    
    path('dashboard/',views.dashboard, name = "dashboard"),
    path('addarticle/',views.addArticle, name = "addarticle"),
    path('article/<int:id>',views.detail, name = "detail"),
    path('update/<int:id>',views.updateArticle, name = "update"),
    path('delete/<int:id>',views.deleteArticle, name = "delete"),
    path('',views.articles, name = "articles"),
    path('comment/<int:id>',views.addComment, name = "comment"),
   
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"), # path bos bırakılarak direkt olarak localhost yazıldığında gidilcek sayfa
    path('about/',views.about, name = "about"),
    path('user/',include("user.urls")),
    # user/login --> user/logout --> user/register gibi url geldiginde user url sayfasında arama yapılacak
    path('articles/',include("article.urls")),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "user"

urlpatterns = [
    
    path('register/', views.register, name = "register"),
    path('login/', views.loginUser, name = "login"),
    path('logout/', views.logoutUser, name = "logout"),
    
]

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{%url 'index'%}">BG BLOG</a>
  
    <div class="collapse navbar-collapse" id="navbarTogglerDemo03">

      <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
        <li class="nav-item active">
          <a class="nav-link" href="{%url 'about' %}">About <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/articles">Articles</a>
        </li>
      </ul>

      <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      {% if  request.user.is_authenticated %}
      <li class="nav-item active">
          <a href="{%url 'article:dashboard' %}" class="nav-link"> Dashboard </a>
      </li>
      <li class="nav-item active">
          <a href="{%url 'user:logout' %}" class="nav-link"> Logout </a>
      </li>

      {% else %}
      <li class="nav-item active">
          <a href="{%url 'user:login' %}" class="nav-link"> Login </a>
      </li>
      <li class="nav-item active">
          <a href="{%url 'user:register' %}" class="nav-link"> Register </a>
      </li>

      {% endif %}
        
      </ul>
      

    </div>
  </nav>