article/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = "article"
# article icerisindeki url yonlendirmelerini buradan yapacagız
# daha moduler hale getirmek icin buna basvurduk

urlpatterns = [
    
    path('dashboard/',views.dashboard, name = "dashboard"),
    path('addarticle/',views.addArticle, name = "addarticle"),
    path('article/<int:id>',views.detail, name = "detail"),
    path('update/<int:id>',views.updateArticle, name = "update"),
    path('delete/<int:id>',views.deleteArticle, name = "delete"),
    path('',views.articles, name = "articles"),
    path('comment/<int:id>',views.addComment, name = "comment"),
   
]

blog/urls.py
from django.contrib import admin
from django.urls import path, include

from article import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('admin/', admin.site.urls),
    path('', views.index, name = "index"), # path bos bırakılarak direkt olarak localhost yazıldığında gidilcek sayfa
    path('about/',views.about, name = "about"),
    path('user/',include("user.urls")),
    # user/login --> user/logout --> user/register gibi url geldiginde user url sayfasında arama yapılacak
    path('articles/',include("article.urls")),
    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User",on_delete = models.CASCADE) # hangi tabloyu gosterdiğini foreign key ile belirtiriz
    title = models.CharField(max_length = 50)
    
    content = RichTextField()
    # richtextfield kullanılabilmesi icin {{myform.media}} seklinde html sayfasında bir kullanıma ihtiyacımız var
    # ayrıca on tarafta bir bozulma olmaması icin ve form yapısıyla uygunluk gostermesi icin settings.py icerisinde bunu confıg ile belirtmeliyiz
    
    createdDate = models.DateTimeField(auto_now=True)
    #tarih otomatik olarak eklenecek
    articleImage = models.FileField(blank=True, null=True ,verbose_name= " Add photo to article ")
    
    def __str__(self):
        return self.title

class Comment(models.Model):
    article = models.ForeignKey(Article,on_delete=models.CASCADE, verbose_name = "Article",related_name="comments")
    comment_author = models.CharField(max_length = 50, verbose_name = "name")
    comment_content = models.CharField(max_length = 200, verbose_name = "comment")
    comment_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.comment_content
        

article/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        # form ile article modeli baglantılı hale getirilmis oldu
        fields = ["title","content","articleImage"]

article/views.py
from django.shortcuts import render,HttpResponse,redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm
from .models import Article, Comment
from django.contrib import messages

# Create your views here.

def articles(request):
    keyword = request.GET.get("keyword")
    if keyword:
        articles = Article.objects.filter(title__contains = keyword)
        return render(request,"articles.html",{"articles": articles})
    
    articles = Article.objects.all()
    
    return render(request, "articles.html",{"articles" : articles} )

def index(request):
    # request her view isleminde olmak zorunda get ve post islemleri icin request kullanılacak
    # view icerisinde ister httpresponse olarak istersek de template seklinde bir return alabiliriz
    #return HttpResponse("<h3> Ana sayfa </h3>")
    return render(request,"index.html")

def about(request):
    return render(request,"about.html")

@login_required(login_url= "user:login")
def dashboard(request):
    articles = Article.objects.filter(author = request.user)
    
    context = {
        "articles" : articles
        # yazara ait tum makaleler sozluk yapısı olarak alınmıs oldu
        # artık on tarafta bunları for donugusu ile yazdırabiliriz
    }
    
    return render(request,"dashboard.html",context)

@login_required(login_url= "user:login")
def addArticle(request):
    form = ArticleForm(request.POST or None, request.FILES or None)
    
    if form.is_valid():
        article = form.save(commit=False)
        # form tarafında author bilgisi alınmadığı icin bunu elle eklememiz gerekmektedir
        # sonrasında database kaydetme islemini gerceklestirebiliriz
        article.author = request.user
        article.save()
        
        articles = Article.objects.filter(author = request.user)
        # update dashboard
        context = {
        "articles" : articles
        }

        messages.success(request,"Article created successfully !")
        return render(request,"dashboard.html",context)
    
    return render(request,"addArticle.html", {"form" : form})

def detail(request,id):
    #article = Article.objects.filter(id = id).first()
    # ilgili id'ye sahip makale icin ozel sayfa olusturmak icin
    # first() bize liste yerine obje donecektir
    
    article = get_object_or_404(Article, id = id)
    comments = article.comments.all()
    
    return render(request,"detail.html",{"article" : article, "comments": comments})

@login_required(login_url= "user:login")
def updateArticle(request,id):
    
    article = get_object_or_404(Article, id = id)
    form = ArticleForm(request.POST or None, request.FILES or None, instance= article)
    # instance --> loading old data
    
    if form.is_valid():
        article = form.save(commit=False)
        article.author = request.user
        article.save()
        
        articles = Article.objects.filter(author = request.user)
        context = {
        "articles" : articles
        }

        messages.success(request,"Article updated successfully !")
        return render(request,"dashboard.html",context)
    
    return render(request,"update.html", {"form" : form})

@login_required(login_url= "user:login")
def deleteArticle(request, id):
    article = get_object_or_404(Article, id= id)
    article.delete()
    messages.success(request,"Article deleted successfully !")
    
    articles = Article.objects.filter(author = request.user)
    context = {
        "articles" : articles
    }
    
    return render(request,"dashboard.html", context)

def addComment(request, id):
    article = get_object_or_404(Article,id = id)
    if request.method == "POST":
        comment_author = request.POST.get("comment_author")
        comment_content = request.POST.get("comment_content")
        
        newComment = Comment(comment_author = comment_author, comment_content = comment_content)
        newComment.article = article
        newComment.save()
    
    # return redirect("/articles/article/" + str(id))
    return redirect(reverse("article:detail",kwargs={"id":id}))
        

templates/about.html
{% extends "layout.html" %}


{% block body %}

    <h3>Hakkımızda</h3>
    <br>
    <p>
        Bu kısım daha sonra ayrıntılı bir şekilde doldurulacaktır.    
    </p>

{% endblock body %}

templates/addArticle.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h3>Create Article</h3>
            <br>
            
            <form method="POST" enctype="multipart/form-data">
            # file upload control

                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger"> Add Article </button>
        
            </form>
        </div>
    </div>

{% endblock body %}

templates/articles.html
{% extends "layout.html" %}

{% block body %}

            
            <div class="row">
                <div class="col-lg-12">

                    <form style="float: right;">    
                        {% csrf_token %}
                        <input type="text" name="keyword" id="search" placeholder="search...">
                        <button type="submit" class="btn btn-primary btn-md">Search</button>
                    </form>

                    <h1>ARTICLES</h1>
                    <hr>
                </div>
            </div>
          
              {% if articles %}

                    {% for article in articles %}
                    <div class="row" style="border-radius: 2%; margin-top: 2%; background-color: #E9ECEF;">
                        <div class="col-lg-12">
                            <!-- Post content-->
                            <article>
                                <!-- Post header-->
                                <header class="mb-4">
                                    <!-- Post title-->
                                    <a href="{% url 'article:detail' article.id %}" style="text-decoration: none">
                                        <!-- /articles/article/{{article.id}} -->
                                        <h2 class="fw-bolder mb-1">{{article.title}}</h2>
                                    </a> 
                                    <!-- Post meta content-->
                                    <p class="text-muted fst-italic mb-2"> <b>Written by {{article.author}}</b></p>
                                    <hr>
                                    <p class="text-muted fst-italic mb-2"> <b style="color: rgb(238, 180, 180);">Posted on {{article.createdDate}}</b></p>
                                    <hr>
                                    
                                </header>
                                <!-- Preview image figure-->
                                {% if article.articleImage %}
                                    <img class="img-fluid rounded" src="{{article.articleImage.url}}" alt="" />
                                {% else %}
                                    <img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." />
                                {% endif %}
                                <hr>
                                <!-- Post content-->
                                <section class="mb-5">
                                    <p>
                                        {{article.content|safe|truncatewords:25}}
                                    </p>
                                    <a href="{% url 'article:detail' article.id %}" class="btn btn-danger" style="float: right;">
                                        Read more
                                    </a>
                                    <hr>
                                </section>
                            </article>
                        </div>
                        <!-- Side widgets-->
                       
                    </div>    
                    {% endfor %}

              {% else %}
              <div class="alert alert-danger">
                There are no posts in this blog...
              </div>
              {% endif %}

        
{% endblock body %}

templates/dashboard.html
{% extends "layout.html" %}

{% block body %}

    <h3>Dashboard</h3>
    <hr>
    <p>
        Hoş geldiniz, <small>{{request.user.username}}</small>
    </p>
    <hr>
    <a href="{%url 'article:addarticle' %}" class="btn btn-danger">Add Article</a>
    <hr>

      {% if articles %}

        <table class="table">
          <thead class="thead-dark">
            <tr>
              <th scope="col">id</th>
              <th scope="col">Title</th>
              <th scope="col">Author</th>
              <th scope="col">Date</th>
              <th scope="col">Update</th>
              <th scope="col">Delete</th>
            </tr>
          </thead>
          <tbody>
          {% for article in articles %}
            <tr>
              <th scope="row">{{article.id}}</th>
                <td> <a href="{%url 'article:detail' article.id%}">{{article.title}}</a></td>
                <td>{{article.author.username}}</td>
                <td>{{article.createdDate}}</td>
                <td><a href="{%url 'article:update' article.id%}" class="btn btn-danger">Update</a></td>
                <td><a href="{%url 'article:delete' article.id%}" class="btn btn-danger">Delete</a></td>
            </tr>
          {% endfor %}

          </tbody>
        </table>

    {% else %}
      <div class="alert alert-danger"> You do not have any articles yet !</div>

    {% endif %}




{% endblock body %}

templates/detail.html
{% extends "layout.html" %}

{% block body %}

<div class="row">
    <div class="col-lg-12">
        <!-- Post content-->
        <article>
            <!-- Post header-->
            <header class="mb-4">
                <!-- Post title-->
                <h2 class="fw-bolder mb-1">{{article.title}}</h2>
                <!-- Post meta content-->
                <p class="text-muted fst-italic mb-2">by {{article.author}}</p>
                <hr>
                <p class="text-muted fst-italic mb-2">Posted on {{article.createdDate}} </p>
                <hr>
                
            </header>
            <!-- Preview image figure-->
            {% if article.articleImage %}
                <img class="img-fluid rounded" src="{{article.articleImage.url}}" alt="" />
            {% else %}
                <img class="img-fluid rounded" src="https://dummyimage.com/900x400/ced4da/6c757d.jpg" alt="..." />
            {% endif %}
            <hr>
            <!-- Post content-->
            <section class="mb-5">
                <p>
                    {{article.content|safe}}
                </p>
            </section>
        </article>
        <br><br>
        <hr>
        <h2 style="color:#0069D9; ">Comments</h2>
        <hr>
        {% if comments %}
        {% for comment in comments %}
            <div class="media mb-4">
                <img class="d-flex mr-3 rounded-circle" src="https://upload.wikimedia.org/wikipedia/commons/7/7c/Profile_avatar_placeholder_large.png" style="height: 50px; width: 50px;" >
                <div class="media-body">
                    <h5 class="mt-0">{{comment.comment_author}}</h5>
                    <b> {{comment.comment_date}} </b><br>
                    {{comment.comment_content}}
                </div>
            </div>
            <hr>
        {% endfor %}
        
        {% else %}
        <div class="alert alert-danger"> Bu makaleye herhangi bir yorum yazılmamıştır.</div>
        {% endif %}

        <div class="card my-4">
            <h5 class="card-header"> Leave a Comment: </h5>
            <div class="card-body">
                <form method="post" action="{% url 'article:comment' article.id %}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="formGroupExampleInput">Name</label>
                        <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Your name" name="comment_author">
                    </div>
                    <div class="form-group">
                        <label for="formGroupExampleInput">Comment</label>
                        <textarea class="form-control" id="" rows="3" name="comment_content"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>   
    </div>
   
</div>

{% endblock body %}

templates/index.html
{% extends "layout.html" %}

{% block body %}

    <div class="jumbotron text-center">

        <h3> Welcome to BG Blog</h3>
        <p>Bu blokta geliştiriciler olarak blog yazılarınızı paylaşabilirsiniz</p>

    </div>

{% endblock body %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>BG Blog</title>
</head>
<body>

    {% include "includes/navbar.html" %}
    <div class="container" style = "margin-top : 4%; margin-bottom: 4%">

        {% if messages %}
            
            {% for message in messages %}
                <div {% if message.tags %} class=" alert alert-{{ message.tags }} col-md-6 offset-md-3"{% endif %}>{{ message }}</div>
            {% endfor %}
            
        {% endif %}

    {% block body %}

        
    {% endblock body %}

    </div>


    <script src="{% static 'js/jquery-3.3.1.slim.min.js'%}"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js"></script>
</body>
</html>

templates/login.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Giriş Yap</h3>
            <br>
            

            <form method="POST">

                {% csrf_token %}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger"> Login </button>
        
            </form>
        </div>
    </div>

{% endblock body %}

templates/register.html
{% extends "layout.html" %}

{% block body %}    
{% load crispy_forms_tags %}

    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h3>Kayıt Ol</h3>
            <br>
            
            <form method="post">

                {% csrf_token %}
                <!-- csrf token ile paraolaların sifrelenerek gonderilmesi saglanır ve man in the middle ataklaraına karsı bir onlem alınmıs olur   form.as_p form gosterimi-->
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger">Kayıt Ol</button>
        
            </form>
            
        </div>
    </div>

{% endblock body %} 

templates/update.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h3>Update Article</h3>
            <br>
            
            <form method="POST" enctype="multipart/form-data">
            # file upload control

                {% csrf_token %}
                {{form.media}}
                {{form|crispy}}
                <br>
                <button type="submit" class="btn btn-danger"> Update </button>
        
            </form>
        </div>
    </div>

{% endblock body %}